class InvalidParamArgument(Exception):...
class MissingParamArgument(Exception):...
class InvalidScheduleTimeError(Exception):...
class InvalidCoroutineFunctionError(Exception):...
class JobNotFoundError(Exception):...
