"""second migration

Revision ID: 7e45931f33ad
Revises: ba8f43c20658
Create Date: 2026-01-18 20:23:16.449396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import zoneinfo


# revision identifiers, used by Alembic.
revision: str = '7e45931f33ad'
down_revision: Union[str, Sequence[str], None] = 'ba8f43c20658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current',
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('feels_c', sa.Float(), nullable=True),
    sa.Column('temp_f', sa.Float(), nullable=True),
    sa.Column('feels_f', sa.Float(), nullable=True),
    sa.Column('humidity', sa.String(), nullable=True),
    sa.Column('wind_kph', sa.Float(), nullable=True),
    sa.Column('wind_mph', sa.Float(), nullable=True),
    sa.Column('wind_dir', sa.Float(), nullable=True),
    sa.Column('time_requested', sa.DateTime(timezone=zoneinfo.ZoneInfo(key='GMT')), nullable=True),
    sa.PrimaryKeyConstraint('city')
    )
    op.create_table('download_manager',
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('is_downloaded', sa.Boolean(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('download_percentage', sa.Integer(), nullable=True),
    sa.Column('date_downloaded', sa.DateTime(timezone=zoneinfo.ZoneInfo(key='GMT')), nullable=True)
    )
    op.create_table('file_logs',
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=True),
    sa.Column('is_downloaded', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=zoneinfo.ZoneInfo(key='GMT')), nullable=True),
    sa.PrimaryKeyConstraint('filename')
    )
    op.create_table('queues',
    sa.Column('func_name', sa.String(), nullable=False),
    sa.Column('args', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=100), nullable=True),
    sa.Column('data', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=zoneinfo.ZoneInfo(key='GMT')), nullable=True),
    sa.PrimaryKeyConstraint('func_name')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=230), nullable=True),
    sa.Column('due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('date_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('alerts',
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('certainty', sa.String(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('effective', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('time_requested', sa.DateTime(timezone=zoneinfo.ZoneInfo(key='GMT')), nullable=True),
    sa.ForeignKeyConstraint(['city'], ['current.city'], ),
    sa.PrimaryKeyConstraint('country')
    )
    op.create_table('forecasts',
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('time_requested', sa.DateTime(timezone=zoneinfo.ZoneInfo(key='GMT')), nullable=True),
    sa.Column('sunrise', sa.DateTime(timezone=zoneinfo.ZoneInfo(key='GMT')), nullable=True),
    sa.Column('sunset', sa.DateTime(timezone=zoneinfo.ZoneInfo(key='GMT')), nullable=True),
    sa.Column('moonrise', sa.DateTime(timezone=zoneinfo.ZoneInfo(key='GMT')), nullable=True),
    sa.Column('moonset', sa.DateTime(timezone=zoneinfo.ZoneInfo(key='GMT')), nullable=True),
    sa.Column('min_temp_c', sa.Float(), nullable=True),
    sa.Column('max_temp_c', sa.Float(), nullable=True),
    sa.Column('avg_temp_c', sa.Float(), nullable=True),
    sa.Column('min_temp_f', sa.Float(), nullable=True),
    sa.Column('max_temp_f', sa.Float(), nullable=True),
    sa.Column('avg_temp_f', sa.Float(), nullable=True),
    sa.Column('maxwind_kph', sa.Float(), nullable=True),
    sa.Column('avgvis_km', sa.Float(), nullable=True),
    sa.Column('maxwind_mph', sa.Float(), nullable=True),
    sa.Column('avgvis_miles', sa.Float(), nullable=True),
    sa.Column('daily_chance_of_rain', sa.Float(), nullable=True),
    sa.Column('daily_chance_of_snow', sa.Float(), nullable=True),
    sa.Column('daily_will_it_rain', sa.Integer(), nullable=True),
    sa.Column('daily_will_it_snow', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['city'], ['current.city'], ),
    sa.PrimaryKeyConstraint('country')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecasts')
    op.drop_table('alerts')
    op.drop_table('tasks')
    op.drop_table('queues')
    op.drop_table('file_logs')
    op.drop_table('download_manager')
    op.drop_table('current')
    # ### end Alembic commands ###
