"""added Log search Column

Revision ID: fcf0e6522047
Revises: 7e45931f33ad
Create Date: 2026-01-30 11:27:49.517630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import zoneinfo


# revision identifiers, used by Alembic.
revision: str = 'fcf0e6522047'
down_revision: Union[str, Sequence[str], None] = '7e45931f33ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=256), nullable=True),
    sa.Column('vector', sa.BLOB(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    # ### end Alembic commands ###
