"""Initial Migration

Revision ID: d00cf1d03606
Revises: 
Create Date: 2026-01-08 20:39:25.238869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00cf1d03606'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configs',
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('default_path', sa.String(length=100), nullable=True),
    sa.Column('default_location', sa.String(length=100), nullable=True),
    sa.Column('api_key', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('category')
    )
    op.create_table('alerts',
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('certainty', sa.String(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('effective', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('time_requested', sa.DateTime(timezone=zoneinfo.ZoneInfo(key='GMT')), nullable=True),
    sa.ForeignKeyConstraint(['city'], ['current.city'], ),
    sa.PrimaryKeyConstraint('country')
    )
    op.drop_table('Configs')
    op.drop_table('Alerts')
    op.drop_table('Weather')
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.alter_column('daily_chance_of_rain',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('daily_chance_of_snow',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('daily_will_it_rain',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('daily_will_it_snow',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.alter_column('daily_will_it_snow',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('daily_will_it_rain',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('daily_chance_of_snow',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('daily_chance_of_rain',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    op.create_table('Weather',
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('condition', sa.VARCHAR(), nullable=True),
    sa.Column('temp_°C', sa.FLOAT(), nullable=True),
    sa.Column('temp_°F', sa.FLOAT(), nullable=True),
    sa.Column('humidiy', sa.VARCHAR(), nullable=True),
    sa.Column('wind_Speed', sa.FLOAT(), nullable=True),
    sa.Column('wind_direction', sa.VARCHAR(), nullable=True)
    )
    op.create_table('Alerts',
    sa.Column('headline', sa.VARCHAR(), nullable=True),
    sa.Column('event', sa.VARCHAR(), nullable=True),
    sa.Column('certainty', sa.VARCHAR(), nullable=True),
    sa.Column('urgency', sa.VARCHAR(), nullable=True),
    sa.Column('severity', sa.VARCHAR(), nullable=True),
    sa.Column('note', sa.VARCHAR(), nullable=True),
    sa.Column('effective', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('instructions', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['city'], ['Weather.city'], )
    )
    op.create_table('Configs',
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('default_path', sa.VARCHAR(length=100), nullable=True),
    sa.Column('default_location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('api_key', sa.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('category')
    )
    op.drop_table('alerts')
    op.drop_table('configs')
    # ### end Alembic commands ###
